export enum EntityType {
    TUTOR_FEEDBACK = 'TUTOR_FEEDBACK',
    CLASS_APPLICATION = 'CLASS_APPLICATION',
    CLASS_REQUIREMENT = 'CLASS_REQUIREMENT',
    CLASS_SESSION = 'CLASS_SESSION',
    CLASS_SESSION_FEEDBACK = 'CLASS_SESSION_FEEDBACK',
}